import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "./_components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(geistMono.variable, geistSans.variable, "antialiased")}
    >
      <body
        className={cn(
          "bg-base-100 text-base-content w-[calc(100vw-2rem) h-[calc(100vh-2rem)] m-4 p-16",
          "border border-base-200 flex-col flex gap-12 rounded-lg"
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
